language: c
os:
  - linux
  - osx
arch:
  - amd64
  - ppc64le
  - arm64

install:
  - ci-base/install.sh travis
  - ./install.sh travis
script: ./run.sh
jobs:
  exclude:
  - os: osx
    arch: ppc64le
  - os: osx
    arch: arm64
