language: c
os:
  - linux
  - osx
arch:
  - amd64
  - ppc64le
  - arm64

install:
  - ci-base/travis_install.sh
  - ./install.sh
script: ./run.sh
jobs:
  exclude:
  - os: osx
    arch: ppc64le
  - os: osx
    arch: arm64
